# generated by fastapi-codegen:
#   filename:  specification.yaml
#   timestamp: 2024-01-29T08:45:07+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Student(BaseModel):
    student_number: int = Field(..., description='the student number of the student')
    name: Optional[str] = Field(None, description='the full of the student')
    degree: Optional[str] = Field(None, description='the degree of the student')
    major: Optional[str] = Field(None, description='the major of the student')


class ErrorType(Enum):
    BadRequest = 'BadRequest'
    Not_Found = 'Not Found'
    InternelServerError = 'InternelServerError'


class Error(BaseModel):
    errorType: Optional[ErrorType] = None
    message: Optional[str] = None


class StudentsPostResponse(BaseModel):
    studentid: Optional[int] = Field(
        None, description='the student number of the newly created student'
    )
