openapi: 3.0.0
info:
  title: Student Management API
  version: 2.0.0
  description: Manage a student's record

servers:
  - url: http://localhost:9000/student_management_api/v2

paths:
  /students:
    post:
      summary: Create a new student
      operationId: createStudent
      description: Create a new student and add them to the collection of students
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Student created successfully
          content:
            application/json:
              schema:
                properties:
                  studentid:
                    type: integer
                    description: the student number of the newly created student
        default:
          $ref: '#/components/schemas/ErrorMessage'
    get:
      summary: Fetch all students
      operationId: getAllStudents
      description: Get a list of all the students
      responses:
        '200':
          description: All students Retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        default:
          $ref: '#/components/responses/ErrorMessage'


  /students/{studentNumber}:
    parameters:
      - in: path
        name: studentNumber
        required: true
        schema:
          type: integer
    get:
      summary: Lookup a Single Student
      operationId: lookupStudent
      description: Find a single student by their student number
      responses:
        '200':
          description: Student Retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        default:
          $ref: '#/components/responses/ErrorMessage'
    put:
      summary: Update Student Details
      operationId: updateStudentDetails
      description: Update the details of a student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        default:
          $ref: '#/components/schemas/ErrorMessage'
    delete:
      summary: Delete a student
      operationId: deleteStudent
      description: Delete a student from the collection
      responses:
        '204':
          description: Student deleted successfully
        default:
          $ref: '#/components/schemas/ErrorMessage'

components:
  schemas:
    Student:
      type: object
      required:
        - student_number
      properties:
        student_number:
          type: integer
          description: the student number of the student
          readOnly: true
        name:
          type: string
          description: the full of the student
        degree:
          type: string
          description: the degree of the student
        major:
          type: string
          description: the major of the student
    
    Error:
      type: object
      properties:
        errorType:
          type: string
          enum:
            - BadRequest

            - Not Found

            - InternelServerError
        message:
          type: string

  responses:
    ErrorMessage:
      description: Exception handling of students and courses
      content:
        application/json:
          schema:
            $ref: '#/compenents/schemas/Error'

